export const CLEAR_CART = "CLEAR_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_ITEM_CART = "INCREASE_ITEM_CART";
export const DECREASE_ITEM_CART = "DECREASE_ITEM_CART";
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";
